### ISSUE TITLE
No color at all after install

### ISSUE THREAD

**Issue by andrew-culver** [yrammos/SubLilyPond#4] opened 2015-01-06 14:20 UTC
Sublime Text 3 Stable Channel Build 3065
SubLilyPond v2014.02.26.09.27.47
No syntax highlighting at all -- tried several color schemes including "Pastels on Dark" "Amy" "Mac classic"

**Comment by andrew-culver** [comment] 2015-01-06 14:28
Discovered that only files ending in '.ily' are treated. This works.
But LilyPond documentation uses '.ly' as a convention.
I suggest including '.ly' as a valid file extension, or is there a way for me to change that, or is there a conflict of some kind prohibiting that?

**Comment by yrammos** [comment] 2015-01-08 22:30
This is puzzling. As you may see in line 3 of https://github.com/yrammos/SubLilyPond/blob/master/LilyPond.JSON-tmLanguage, both file extensions are acknowledged. What happens if you open the .ly file and then manually enable LilyPond syntax highlighting on it?

**Comment by yrammos** [comment] 2015-01-11 13:07
I am going to close this issue as I am unable to reproduce it. Please feel free to reopen it if it persists on your end. Thank you.

**Closed by yrammos** 2015-01-11 13:07 UTC

**Comment by andrew-culver** [comment] 2015-01-11 19:01
Yannis,

That’s good. I can’t reproduce it again either. Probably the play-in was not fully loaded in the .ly sublime window but was in the .ily window. 

Thank you for your efforts bringing LilyPond to Sublime. A great combination.

Andrew Culver
